# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20161122_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_v1', to=settings.AUTH_USER_MODEL),
        ),
    ]
