# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='analytics_opt_out',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default='TOKEN', max_length=200),
            preserve_default=False,
        ),
    ]
