# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles2', '0002_auto_20170803_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='auth_token',
        ),
    ]
