# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles2', '0003_auto_20170804_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
