# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles2', '0004_auto_20170804_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='TEMP USERNAME', max_length=200),
            preserve_default=False,
        ),
    ]
