# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles2', '0005_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
