# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 15:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stories2.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('story_count', models.IntegerField(default=0, verbose_name='Story Count')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('anonymous', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='stories2.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('feed_url', models.URLField()),
                ('logo', models.ImageField(upload_to=stories2.models.s3_image_upload)),
                ('last_update', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('pub_id', models.IntegerField(verbose_name='Publication ID')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('content', models.TextField(verbose_name='Raw Content')),
                ('text', models.TextField(verbose_name='Text Content')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('categories', models.ManyToManyField(related_name='stories', to='stories2.Category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories2.Publication')),
            ],
            options={
                'ordering': ('publisher', 'pub_date'),
            },
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=stories2.models.s3_image_upload, verbose_name='Image')),
                ('sequence', models.IntegerField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories2.Story')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories2.Story'),
        ),
        migrations.AlterUniqueTogether(
            name='commentupvote',
            unique_together=set([('comment', 'author')]),
        ),
    ]
