# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stories.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to=stories.models.s3_image_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('authors', models.TextField()),
                ('image', models.ImageField(upload_to=stories.models.s3_image_upload)),
                ('caption', models.TextField()),
                ('content', models.TextField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Publication')),
            ],
        ),
    ]
