# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='feed_url',
            field=models.URLField(default='http://thecampanile.org/feed/'),
            preserve_default=False,
        ),
    ]
