# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories2', '0002_auto_20170803_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories2.Category'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='topics', to='stories2.Story'),
        ),
    ]
