# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20160901_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(default='NO TEXT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(related_name='stories', to='stories.Category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.Publication'),
        ),
    ]
