# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories2', '0003_auto_20170804_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('publisher', 'pub_date'), 'verbose_name_plural': 'stories'},
        ),
    ]
