# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stories2', '0004_auto_20170804_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('weight', models.FloatField(default=0, verbose_name='Weight')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_stories2.feedentry_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='story',
            name='active',
        ),
        migrations.RemoveField(
            model_name='story',
            name='id',
        ),
        migrations.RemoveField(
            model_name='story',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
        migrations.RemoveField(
            model_name='story',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='active',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='weight',
        ),
        migrations.AddField(
            model_name='story',
            name='feedentry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stories2.FeedEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='feedentry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stories2.FeedEntry'),
            preserve_default=False,
        ),
    ]
