# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories2', '0006_auto_20170804_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedentry',
            options={'ordering': ['weight']},
        ),
        migrations.AlterField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories2.Category'),
        ),
    ]
