# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories2', '0007_auto_20170804_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
