# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20160906_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
