# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories2', '0009_auto_20170804_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedentry',
            options={'ordering': ['-weight']},
        ),
        migrations.AddField(
            model_name='storyimage',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
