# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20160915_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='story_count',
            field=models.IntegerField(default=0, verbose_name='Story Count'),
        ),
    ]
