# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_publication_feed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=stories.models.s3_image_upload)),
                ('caption', models.TextField(blank=True)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.AddField(
            model_name='publication',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='story',
            name='pub_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storyimage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(to='stories.Category'),
        ),
    ]
