# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20160904_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('publisher', 'pub_date')},
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
