# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import stories.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=stories.models.s3_image_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='story',
            name='authors',
            field=models.TextField(verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(verbose_name='Raw Content'),
        ),
        migrations.AlterField(
            model_name='story',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='story',
            name='pub_id',
            field=models.IntegerField(verbose_name='Publication ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
