# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stories.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_category_story_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storyimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=stories.models.s3_image_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.Story'),
        ),
    ]
