# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20161122_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_v1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentupvote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes_v1', to=settings.AUTH_USER_MODEL),
        ),
    ]
